name: ðŸš€ Pipeline

on:
  workflow_dispatch:
  push:
    tags:
            # r1, r2, r3 | YYwWWa, YYwWWb, YYwWW~
      - "(?:(^r{1}[0-9]+)|([0-9]{2}w[0-9]{2}[a-z~]{1}))"

env:
  DOCKER_BUILDKIT: 1
  EXPORT_NAME: munch

jobs:
  build-export-container:
    name: Build export container
    runs-on: ubuntu-22.04
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ðŸ³ Docker Build
        run: |
          docker build -t ghrc.io/zrckr/godot/export ./docker
      
      - name: ðŸ“¦ Push to ghcr.io
        uses: pyTooling/Actions/with-post-step@r0
        with:
          main: |
            echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
            docker push ghcr.io/zrckr/godot/export
          post: docker logout ghcr.io
  
  export-project:
    name: Export for ${{ matrix.name }}
    runs-on: ubuntu-22.04
    needs: build-export-container
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: Web
            path: ./dist/web/index.html
            name: Web
            upload: .github/dist/web/*
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3
      
      - name: ðŸ“ Create folder
        run: |
          mkdir -p .github/dist/"$(dirname '${{ matrix.path }}')"
          cp .github/dist/export_presets.cfg .

      - name: ðŸ”¨ Export project
        uses: docker://ghrc.io/zrckr/godot/export
        env:
          GODOT_EXPORT_SUBDIR: .github
        with:
          args: export --export-release ${{ matrix.name }} ${{ matrix.path }}
      
      - name: ðŸ“¤ Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.upload }}
          if-no-files-found: error

  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-22.04
    needs: export-project
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ðŸ“¥ Download the Web artifact
        uses: actions/download-artifact@v3
        with:
          name: Web
          path: public/play
      
      - name: ðŸ” Show the directory
        run: tree public
      
      # Workaround for SharedArrayBuffer support on GitHub Pages
      # See: https://github.com/godotengine/godot-docs/issues/7084
      - name: ðŸ©¹ Patch the `index.html`
        run: |
          cd public/play
          curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js > coi-serviceworker.js
          sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.js"></script>\n\1#g' index.html
      
      - name: ðŸš€ Publish to GitHub Pages
        run: |
          cd public
          touch .nojekyll
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "${GITHUB_ACTOR}"
          git config --local user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -a -m "feat: update GitHub Pages with ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages